// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package comet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CometClient is the client API for Comet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CometClient interface {
	PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgReply, error)
	NewFriendShipApplyNotice(ctx context.Context, in *NewFriendShipApplyNoticeReq, opts ...grpc.CallOption) (*NewFriendShipApplyNoticeReply, error)
	FriendShipApplyPassNotice(ctx context.Context, in *FriendShipApplyPassReq, opts ...grpc.CallOption) (*FriendShipApplyPassReply, error)
}

type cometClient struct {
	cc grpc.ClientConnInterface
}

func NewCometClient(cc grpc.ClientConnInterface) CometClient {
	return &cometClient{cc}
}

func (c *cometClient) PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgReply, error) {
	out := new(PushMsgReply)
	err := c.cc.Invoke(ctx, "/maoim.comet.Comet/PushMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) NewFriendShipApplyNotice(ctx context.Context, in *NewFriendShipApplyNoticeReq, opts ...grpc.CallOption) (*NewFriendShipApplyNoticeReply, error) {
	out := new(NewFriendShipApplyNoticeReply)
	err := c.cc.Invoke(ctx, "/maoim.comet.Comet/NewFriendShipApplyNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) FriendShipApplyPassNotice(ctx context.Context, in *FriendShipApplyPassReq, opts ...grpc.CallOption) (*FriendShipApplyPassReply, error) {
	out := new(FriendShipApplyPassReply)
	err := c.cc.Invoke(ctx, "/maoim.comet.Comet/FriendShipApplyPassNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CometServer is the server API for Comet service.
// All implementations must embed UnimplementedCometServer
// for forward compatibility
type CometServer interface {
	PushMsg(context.Context, *PushMsgReq) (*PushMsgReply, error)
	NewFriendShipApplyNotice(context.Context, *NewFriendShipApplyNoticeReq) (*NewFriendShipApplyNoticeReply, error)
	FriendShipApplyPassNotice(context.Context, *FriendShipApplyPassReq) (*FriendShipApplyPassReply, error)
	mustEmbedUnimplementedCometServer()
}

// UnimplementedCometServer must be embedded to have forward compatible implementations.
type UnimplementedCometServer struct {
}

func (UnimplementedCometServer) PushMsg(context.Context, *PushMsgReq) (*PushMsgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMsg not implemented")
}
func (UnimplementedCometServer) NewFriendShipApplyNotice(context.Context, *NewFriendShipApplyNoticeReq) (*NewFriendShipApplyNoticeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewFriendShipApplyNotice not implemented")
}
func (UnimplementedCometServer) FriendShipApplyPassNotice(context.Context, *FriendShipApplyPassReq) (*FriendShipApplyPassReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendShipApplyPassNotice not implemented")
}
func (UnimplementedCometServer) mustEmbedUnimplementedCometServer() {}

// UnsafeCometServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CometServer will
// result in compilation errors.
type UnsafeCometServer interface {
	mustEmbedUnimplementedCometServer()
}

func RegisterCometServer(s grpc.ServiceRegistrar, srv CometServer) {
	s.RegisterService(&Comet_ServiceDesc, srv)
}

func _Comet_PushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).PushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/maoim.comet.Comet/PushMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).PushMsg(ctx, req.(*PushMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_NewFriendShipApplyNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewFriendShipApplyNoticeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).NewFriendShipApplyNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/maoim.comet.Comet/NewFriendShipApplyNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).NewFriendShipApplyNotice(ctx, req.(*NewFriendShipApplyNoticeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_FriendShipApplyPassNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendShipApplyPassReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).FriendShipApplyPassNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/maoim.comet.Comet/FriendShipApplyPassNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).FriendShipApplyPassNotice(ctx, req.(*FriendShipApplyPassReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Comet_ServiceDesc is the grpc.ServiceDesc for Comet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Comet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maoim.comet.Comet",
	HandlerType: (*CometServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMsg",
			Handler:    _Comet_PushMsg_Handler,
		},
		{
			MethodName: "NewFriendShipApplyNotice",
			Handler:    _Comet_NewFriendShipApplyNotice_Handler,
		},
		{
			MethodName: "FriendShipApplyPassNotice",
			Handler:    _Comet_FriendShipApplyPassNotice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/comet/comet.proto",
}
