mysql:
  host: 127.0.0.1
  port: 6033
  username: root
  password: 123456
  db_name: maoim

redis:
  host: 127.0.0.1
  port: 9736
  password: Zhangjinyi0
  db: 0

logic:
  port: 8001

assemble:
  port: 9130
