// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"maoim/api/comet"
	"maoim/internal/logic"
	"maoim/internal/logic/message"
	"maoim/internal/logic/user"
	"maoim/pkg/redis"
)

// Injectors from wire.go:

func Init(rdb *redis.Redis, g *gin.Engine, cometClient comet.CometClient) *logic.Server {
	dao := message.NewDao(cometClient)
	userDao := user.NewDao(rdb)
	service := user.NewService(userDao)
	messageService := message.NewService(dao, service)
	api := message.NewApi(messageService, g)
	userApi := user.NewApi(service, g)
	server := logic.New(api, userApi, g)
	return server
}
